site_name: arxiv2026_hierarchical_latent_structures
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: arxiv2026_hierarchical_latent_structures
      handlers:
        python:
          options:
            docstring_style: numpy