experiment_name: "ngram_large"
num_experiments_per_grammar: 1
param_ranges:
  vocab_size: [1000]
  context_window: [512]
  model_dim: [256]
  num_layers: [16]
  num_heads: [4]
  architecture: ["llama"]

languages:
  - ngram:
      order: 10
      min_length: 10
      num_sentences: 5_000_000_000
      zipf_mu: 2.0
      zipf_sigma: 1.2
      length_zipf_exponent: 2.0
      min_exponent: 1.2

external_experiment_path: "/p/scratch/westai0065/experiments"
mode: sequential